#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, like "SHELL=/bin/bash ./gradlew"
#       or "export SHELL=/bin/bash; ./gradlew".
#
#   (2) The script will attempt to find a 'java' command on your path. If you
#       have set the JAVA_HOME environment variable, that will be used. However,
#       you can also set the GRADLE_JAVA_CMD environment variable to explicitly
#       set the 'java' command to use.
#
#       If you cannot find a 'java' command on your path and have not set
#       GRADLE_JAVA_CMD or JAVA_HOME, Gradle will use a 'java' installed under
#       the directory specified by the `GRADLE_USER_HOME` environment variable.
#
#       If none of those are set, Gradle will try to download a JDK and install
#       it under the directory specified by `GRADLE_USER_HOME` (or the gradle
#       project property `gradle.user.home`).
#
#       If you have set `GRADLE_USER_HOME`, but Gradle cannot find an appropriate
#       JDK, you might consider installing one manually.
#
#   (3) If you run this script with the `GRADLE_USER_HOME` pointing to a location
#       from which Gradle has not previously downloaded a JDK, it will attempt
#       to download a JDK and place it there. If that fails, the build will fail.
#
#       You can avoid the JDK download by setting the `JAVA_HOME` environment
#       variable to point to a Java 17+ installation on your build machine.
#
#   (4) To avoid the per-build JDK download, you can also use the
#       `-Dorg.gradle.java.installations.fromEnv` flag to point Gradle to one
#       or more local JDK installations.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not available. Use the 'make' (or 'gmake') and 'nproc' commands if available.
        # We use 'make' to avoid a too-high dependency on 'nproc' (which is not available on all platforms).
        # MAX_FD is used by Gradle's `help` task to display the value. We do not actually use it.
        # shellcheck disable=SC2034
        MAX_FD=$( ( ulimit -H -n ||: ) 2>/dev/null | tail -n1 || echo 4096 )
        ;;
      *)
        MAX_FD=$( ulimit -n || echo 4096 )
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module-path is given)
#   * --module (main module)
#   * together with ALL properties from the property-file (if any)
#   * JVM arguments (if any)
#   * final class (normally org.gradle.wrapper.GradleWrapperMain)
#   * configuration directory (normally the same as the one containing gradlew)

# Collect properties from any gradle.properties files, but only if we wouldn't
# exceed the maximum number of arguments (for the command line) or the
# property file defines a lot of properties (to overflow the environment
# buffers).
MAX_ENV_ARGS=10000
ENV_NAMES=""
arg_properties=
max_system_properties=0
max_project_properties=0

# We may need to pass the `-D' properties to the JVM because the ant task
# might pass them through to the Gradle OOTB launcher incorrectly (as JVM
# arguments rather than properties). However `-D` as JVM arg appears to work
# fine, so we don't actively prevent '-D' being passed as JVM arg.
system_properties=
project_properties=

# Optimize for large property counts.
check_env_overflow() {
    if [ $# -gt $MAX_ENV_ARGS ]; then
        echo "The env couldn't be saved to the current process's arguments because it would exceed the maximum argument limit." >&2
        exit 1
    fi
    count=0
    for arg in "$@"; do
        if [ "$arg" = "org.gradle.internal.splashscreen.ShowSplashScreen" ]; then
            continue
        fi
        count=$((count + 1))
        if [ $count -eq $MAX_ENV_ARGS ]; then
            echo "The env couldn't be saved to the current process's arguments because it would exceed the maximum argument limit." >&2
            exit 1
        fi
    done
}

# Helper function for extracting properties from a file.
extract_properties() {
    local properties_file="$1"
    if [ -f "$properties_file" ]; then
        echo "Reading properties from $properties_file"
        local line_nr=0
        while IFS= read -r line; do
            line_nr=$((line_nr + 1))
            line="${line##+([[:space:]])}"
            if [ -z "$line" ]; then continue; fi
            case "$line" in
                \#*)
                    continue
                    ;;
                *=*)
                    name=${line%%=*}
                    value="${line#*=}"
                    name="${name// /}"
                    # Removing surrounding quotes from the value
                    case "$value" in
                        \"*\")
                            value="${value#\"}"
                            value="${value%\"}"
                            ;;
                    esac
                    case "$name" in
                        org.gradle.jvmargs|org.gradle.daemon.debug|org.gradle.parallel)
                            # We want these to be passed as JVM args, not properties
                            ;;
                        *)
                            project_properties="$project_properties -D$name=$value"
                            ;;
                    esac
                    ;;
                *)
                    warn "Properties file $properties_file contains an invalid line at line $line_nr: $line
Please check the file and remove invalid lines." >&2
            esac
        done < "$properties_file"
    fi
}

# Append the JVM args (in a property cycle) to the command line.
read_and_append_jvm_args() {
    # We could also iterate over the contents of the JVM args property file.
    # However it's not needed because the properties evaluation is more complete.
    local maybe_project_properties
    while [ $# -ne 0 ]; do
        maybe_project_properties="$1"
        shift
        if [ -n "$maybe_project_properties" ]; then
            # Ensure that we place everything coming from the properties file
            # at the end of the JVM arguments to avoid replacing arguments
            # when they appear on the command line.
            jvm_args="$maybe_project_properties $jvm_args"
        fi
    done

    # Append builtin JVM arguments from the environment.
    # We use the 'IFS' to ensure lines are treated as elements,
    # and 'set -f' to avoid globbing.
    if [ -n "$GRADLE_OPTS" ]; then
        IFS=" " ; set -f
        jvm_args="$GRADLE_OPTS $jvm_args"
        set +f
        unset IFS
    fi
    if [ -n "$JAVA_OPTS" ]; then
        IFS=" " ; set -f
        jvm_args="$JAVA_OPTS $jvm_args"
        set +f
        unset IFS
    fi
    # "-Dorg.gradle.launcher.splashscreen=true" is already included in the default Gradle command line.
    # Docker pulls the OpenJ9 image, which adds '-XX:+UseContainerSupport' to the JAVA_OPTS.
    # This causes a usage of '--module-path' which is currently unsupported by the OpenJ9 JDK.
    # The best workaround is to filter it out.
    # shellcheck disable=SC2001
    jvm_args=$(echo "$jvm_args" | sed 's/ -XX:+UseContainerSupport//')

    jvm_args_count=0
    for arg in $jvm_args; do
        jvm_args_count=$((jvm_args_count+1))
        # Avoid expanding the empty argument.
        if [ -n "$arg" ]; then
            jvm_args_list="$jvm_args_list \"$arg\""
        fi
    done
}

# Collect arguments in the order we will add them to the command line.
collect_args() {
    # Collect the command line arguments up to the first '--' that indicates the
    # end of the JVM arguments and the start of the Gradle command arguments.
    # If there are no arguments after '--', then the '--' is assumed to be part
    # of a command line argument that we should ignore.
    # The arguments are stored in reverse order in a local variable.
    local maybe_app_args=
    local split_marker_found=

    while [ $# -ne 0 ] && [ -z "$split_marker_found" ]; do
        arg="$1"
        shift
        if [ "--" = "$arg" ]; then
            split_marker_found=true
            continue
        fi
        if [ -n "$maybe_app_args" ]; then
            # Already collecting the Gradle arguments.
            maybe_app_args="$arg $maybe_app_args"
        elif [ "${arg#-D}" != "$arg" ] || [ "${arg#-d}" != "$arg" ]; then
            # This is a JVM argument, so we add it at the front.
            jvm_args_list="$arg $jvm_args_list"
        else
            maybe_app_args="$arg $maybe_app_args"
        fi
    done

    # The app arguments we collected (if any) belong to the --some-option value,
    # which means they are not part of the main class arguments (the ones that
    # we should pass to Gradle). However, we collect them as if they could be
    # part of a task that uses '--app-args', which currently isn't a thing in
    # Gradle. But we leave it in case something external to Gradle expects them.
    if [ -n "$maybe_app_args" ]; then
        app_args_list="$maybe_app_args"
    fi

    # Collect the arguments that should be passed to the main class.
    main_class_args="$app_args_list $main_class_args"
}

# Check that we have a `gradle/wrapper/gradle-wrapper.jar` file. If not, download it.
# We might download it lazily if the JDK we downloaded also provides it.
cd "$APP_HOME" || exit
if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
    if ! download_gradle; then
        die "Could not find Gradle wrapper JAR. Please download it manually or place it in 'gradle/wrapper/gradle-wrapper.jar'."
    else
        # We need to add a flag so the wrapper knows we already downloaded the JAR.
        wrapper_already_downloaded=1
    fi
fi

# Now we can start.
collect_args "$@"
read_and_append_jvm_args "$system_properties" "$project_properties"

# Setup the appropriate classpath.
classpath="gradle/wrapper/gradle-wrapper.jar"
if [ -n "$wrapper_already_downloaded" ]; then
    # The JAR was downloaded, so we add it to the classpath.
    classpath="gradle/wrapper/gradle-wrapper.jar"
fi

# Execute the Java command using the classpath and the main class.
execute "$JAVACMD" $jvm_args_list -classpath "$classpath" org.gradle.wrapper.GradleWrapperMain $main_class_args
